name: Square Atom Flutter CI
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: flutter-ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  quality:
    uses: squareatomhq/.github/.github/workflows/reusable-flutter-ci.yml@main
